### ISSUE TITLE
Error in Test api section related to refresh token. 

### ISSUE THREAD

**Issue by leonard4546** [HarryVed/Microsoft-Developer-Subscription-Renew-Free#1]
Hey, I'm getting following error in Test api section of workflow, do you have any idea about that?

Run echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
  echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
  python3 temp.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.18/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.9.18/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.18/x64
    Python[2](https://github.com/leonard4546/e5/actions/runs/7624887232/job/20767987455#step:6:2)_ROOT_DIR: /opt/hostedtoolcache/Python/[3](https://github.com/leonard4546/e5/actions/runs/7624887232/job/20767987455#step:6:3).9.18/x6[4](https://github.com/leonard4546/e5/actions/runs/7624887232/job/20767987455#step:6:4)
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.18/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.18/x64/lib
Traceback (most recent call last):
  File "/home/runner/work/e[5](https://github.com/leonard4546/e5/actions/runs/7624887232/job/20767987455#step:6:5)/e5/temp.py", line 83, in <module>
    main()
  File "/home/runner/work/e5/e5/temp.py", line [6](https://github.com/leonard4546/e5/actions/runs/7624887232/job/20767987455#step:6:6)2, in main
    access_token = get_access_token(refresh_token, client_id, client_secret)
  File "/home/runner/work/e5/e5/temp.py", line 55, in get_access_token
    refresh_token = jsontxt['refresh_token']
KeyError: 'refresh_token'
Error: Process completed with exit code 1.

**Comment by o-gui-blindao** [comment]
Did you create your tokens as variables or secret (btw this is a fork not the master branch)
